version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - database

  database:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "123456"
      MSSQL_PID: "Express"
      MSSQL_SA_PASSWORD: "123456"
      MSSQL_ALLOW_EMPTY_PASSWORD: "Y"
      MSSQL_AUTHENTICATION: "SqlPassword"
    ports:
      - "1433:1433"